base_url = "https://lzahq.tech"
title = "lzahq"
compile_sass = false
build_search_index = true
theme = "DeepThought"
minify_html = true
ignored_content = []
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", fees = true, paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]
mermaid.enabled = true
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/projects", name = "Projects" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]}
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/images/favicon-16x16.png"
favicon_32x32 = "/images/favicon-32x32.png"
apple_touch_icon = "/images/apple-touch-icon.png"
safari_pinned_tab = "/images/safari-pinned-tab.svg"
webmanifest = "/images/site.webmanifest"

[extra.author]
name = "lza"
avatar = "/images/shitbird.png"
zavatar = "/images/lza.jpg"

[extra.social]
email = "lance@lzahq.tech"
github = "lalanza808"
twitter = "lza_menace"

[extra.analytics]
google = "UA-60618938-4"

[extra.commenting]
# disqus = "<your_disqus_shortname>"
